quarkus.datasource.db-kind = mysql 

quarkus.hibernate-orm.schema-management.strategy=update 

quarkus.datasource.username = monitor
quarkus.datasource.password = monitor
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/monitordata

quarkus.rest-client.device-data-api.url=http://localhost:8080/api
